config/routes.rb
Rails.application.routes.draw do
  root to: 'messages#index'

  resources :messages  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  validates :content, presence: true, length: { maximum: 255} # カラ禁止かつ255字以内
  validates :title, presence: true, length: { maximum: 255} # カラ禁止かつ255字以内
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend # ページネーション設定
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]
  
  def index
    @pagy, @messages = pagy(Message.order(id: :desc), items: 25) # Messageレコードを全て取得して、@messages（インスタンス変数）に代入
  end

  def show
  end

  def new
    @message = Message.new
  end

  def create
    @message = Message.new(message_params)
    
    if @message.save
      flash[:success] = "メッセージが正常に投稿されました"
      redirect_to @message
    else
      flash.now[:danger] = "メッセージの投稿に失敗しました"
      render :new
    end
  end

  def edit
  end

  def update
    if @message.update(message_params)
      flash[:success] = "メッセージが更新されました"
      redirect_to @message
    else
      flash.now[:danger] = "メッセージの更新に失敗しました"
      render :edit
    end
  end

  def destroy
    @message.destroy
    
    flash[:success] = "メッセージは削除されました"
    redirect_to root_url
  end
  
  private # Strong Parameter
  
  def set_message
    @message = Message.find(params[:id])
  end
  
  def message_params # newからcreateへ送られてきたフォームの内容の代入
    params.require(:message).permit(:content, :title) 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div><%= message %></div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <title>メッセージボード</title>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= render "layouts/flash_messages" %>
      
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_form.html.erb
<%= form_with(model: @message) do |f| %> <!--フォームの設置-->
  <% if message.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% message.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <%= f.label :title, "タイトル" %>
  <%= f.text_field :title %>

  <%= f.label :content, "メッセージ" %>
  <%= f.text_field :content %>
  
  <%= f.submit "投稿" %> <!--送信ボタン-->
<% end %>

app/views/messages/edit.html.erb
<h1>id: <%= @message.id %>のメッセージ編集ページ</h1>

<%= render "form", message: @message %>

<%= link_to "トップページに戻る", root_path %>

app/views/messages/index.html.erb
<h1>メッセージ一覧</h1>

<ul>
  <% @messages.each do |message| %> <!--Controllerで定義した @messages というレコード群からレコードを１つずつ取り出す-->
    <li><%= link_to message.id, message %> : <%= message.title %> &gt; <%= message.content %></li> <!--contentカラムの値を表示-->
  <% end %>
</ul>
<%== pagy_nav(@pagy) %>

<%= link_to "新規メッセージの投稿", new_message_path %>

<!---->

app/views/messages/new.html.erb
<h1>メッセージ新規作成ページ</h1>

<%= render "form", message: @message %>

<%= link_to "トップページに戻る", root_path %>

<!---->

app/views/messages/show.html.erb
<h1>id: <%= @message.id %>のメッセージ詳細ページ</h1>

<p>タイトル: <%= @message.title %></p>
<p>メッセージ: <%= @message.content %></p>

<%= link_to "トップページに戻る", root_path %>
<%= link_to "このメッセージを編集する", edit_message_path(@message) %>
<%= link_to "このメッセージを削除する", @message, method: :delete, data: { confirm: "本当に削除してよろしいですか？" } %>